<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math" exclude-result-prefixes="xs math"
    version="3.0">

    <!-- should add a function to update this from the RDF file at id.loc.gov -->
    <xsl:variable name="cached-list-of-relators">
        <relators>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/abr</uri>
                <code>abr</code>
                <label>Abridger</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/acp</uri>
                <code>acp</code>
                <label>Art copyist</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/act</uri>
                <code>act</code>
                <label>Actor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/adi</uri>
                <code>adi</code>
                <label>Art director</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/adp</uri>
                <code>adp</code>
                <label>Adapter</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/aft</uri>
                <code>aft</code>
                <label>Author of afterword, colophon, etc.</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/anl</uri>
                <code>anl</code>
                <label>Analyst</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/anm</uri>
                <code>anm</code>
                <label>Animator</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ann</uri>
                <code>ann</code>
                <label>Annotator</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ant</uri>
                <code>ant</code>
                <label>Bibliographic antecedent</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ape</uri>
                <code>ape</code>
                <label>Appellee</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/apl</uri>
                <code>apl</code>
                <label>Appellant</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/app</uri>
                <code>app</code>
                <label>Applicant</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/aqt</uri>
                <code>aqt</code>
                <label>Author in quotations or text abstracts</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/arc</uri>
                <code>arc</code>
                <label>Architect</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ard</uri>
                <code>ard</code>
                <label>Artistic director</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/arr</uri>
                <code>arr</code>
                <label>Arranger</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/art</uri>
                <code>art</code>
                <label>Artist</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/asg</uri>
                <code>asg</code>
                <label>Assignee</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/asn</uri>
                <code>asn</code>
                <label>Associated name</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ato</uri>
                <code>ato</code>
                <label>Autographer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/att</uri>
                <code>att</code>
                <label>Attributed name</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/auc</uri>
                <code>auc</code>
                <label>Auctioneer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/aud</uri>
                <code>aud</code>
                <label>Author of dialog</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/aui</uri>
                <code>aui</code>
                <label>Author of introduction, etc.</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/aus</uri>
                <code>aus</code>
                <label>Screenwriter</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/aut</uri>
                <code>aut</code>
                <label>Author</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/bdd</uri>
                <code>bdd</code>
                <label>Binding designer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/bjd</uri>
                <code>bjd</code>
                <label>Bookjacket designer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/bkd</uri>
                <code>bkd</code>
                <label>Book designer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/bkp</uri>
                <code>bkp</code>
                <label>Book producer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/blw</uri>
                <code>blw</code>
                <label>Blurb writer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/bnd</uri>
                <code>bnd</code>
                <label>Binder</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/bpd</uri>
                <code>bpd</code>
                <label>Bookplate designer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/brd</uri>
                <code>brd</code>
                <label>Broadcaster</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/brl</uri>
                <code>brl</code>
                <label>Braille embosser</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/bsl</uri>
                <code>bsl</code>
                <label>Bookseller</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cas</uri>
                <code>cas</code>
                <label>Caster</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ccp</uri>
                <code>ccp</code>
                <label>Conceptor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/chr</uri>
                <code>chr</code>
                <label>Choreographer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cli</uri>
                <code>cli</code>
                <label>Client</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cll</uri>
                <code>cll</code>
                <label>Calligrapher</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/clr</uri>
                <code>clr</code>
                <label>Colorist</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/clt</uri>
                <code>clt</code>
                <label>Collotyper</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cmm</uri>
                <code>cmm</code>
                <label>Commentator</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cmp</uri>
                <code>cmp</code>
                <label>Composer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cmt</uri>
                <code>cmt</code>
                <label>Compositor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cnd</uri>
                <code>cnd</code>
                <label>Conductor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cng</uri>
                <code>cng</code>
                <label>Cinematographer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cns</uri>
                <code>cns</code>
                <label>Censor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/coe</uri>
                <code>coe</code>
                <label>Contestant-appellee</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/col</uri>
                <code>col</code>
                <label>Collector</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/com</uri>
                <code>com</code>
                <label>Compiler</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/con</uri>
                <code>con</code>
                <label>Conservator</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cor</uri>
                <code>cor</code>
                <label>Collection registrar</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cos</uri>
                <code>cos</code>
                <label>Contestant</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cot</uri>
                <code>cot</code>
                <label>Contestant-appellant</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cou</uri>
                <code>cou</code>
                <label>Court governed</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cov</uri>
                <code>cov</code>
                <label>Cover designer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cpc</uri>
                <code>cpc</code>
                <label>Copyright claimant</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cpe</uri>
                <code>cpe</code>
                <label>Complainant-appellee</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cph</uri>
                <code>cph</code>
                <label>Copyright holder</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cpl</uri>
                <code>cpl</code>
                <label>Complainant</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cpt</uri>
                <code>cpt</code>
                <label>Complainant-appellant</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cre</uri>
                <code>cre</code>
                <label>Creator</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/crp</uri>
                <code>crp</code>
                <label>Correspondent</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/crr</uri>
                <code>crr</code>
                <label>Corrector</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/crt</uri>
                <code>crt</code>
                <label>Court reporter</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/csl</uri>
                <code>csl</code>
                <label>Consultant</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/csp</uri>
                <code>csp</code>
                <label>Consultant to a project</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cst</uri>
                <code>cst</code>
                <label>Costume designer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ctb</uri>
                <code>ctb</code>
                <label>Contributor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cte</uri>
                <code>cte</code>
                <label>Contestee-appellee</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ctg</uri>
                <code>ctg</code>
                <label>Cartographer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ctr</uri>
                <code>ctr</code>
                <label>Contractor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cts</uri>
                <code>cts</code>
                <label>Contestee</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ctt</uri>
                <code>ctt</code>
                <label>Contestee-appellant</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cur</uri>
                <code>cur</code>
                <label>Curator</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/cwt</uri>
                <code>cwt</code>
                <label>Commentator for written text</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dbp</uri>
                <code>dbp</code>
                <label>Distribution place</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dfd</uri>
                <code>dfd</code>
                <label>Defendant</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dfe</uri>
                <code>dfe</code>
                <label>Defendant-appellee</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dft</uri>
                <code>dft</code>
                <label>Defendant-appellant</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dgg</uri>
                <code>dgg</code>
                <label>Degree granting institution</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dgs</uri>
                <code>dgs</code>
                <label>Degree supervisor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dis</uri>
                <code>dis</code>
                <label>Dissertant</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dln</uri>
                <code>dln</code>
                <label>Delineator</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dnc</uri>
                <code>dnc</code>
                <label>Dancer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dnr</uri>
                <code>dnr</code>
                <label>Donor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dpc</uri>
                <code>dpc</code>
                <label>Depicted</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dpt</uri>
                <code>dpt</code>
                <label>Depositor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/drm</uri>
                <code>drm</code>
                <label>Draftsman</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/drt</uri>
                <code>drt</code>
                <label>Director</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dsr</uri>
                <code>dsr</code>
                <label>Designer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dst</uri>
                <code>dst</code>
                <label>Distributor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dtc</uri>
                <code>dtc</code>
                <label>Data contributor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dte</uri>
                <code>dte</code>
                <label>Dedicatee</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dtm</uri>
                <code>dtm</code>
                <label>Data manager</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dto</uri>
                <code>dto</code>
                <label>Dedicator</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/dub</uri>
                <code>dub</code>
                <label>Dubious author</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/edc</uri>
                <code>edc</code>
                <label>Editor of compilation</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/edm</uri>
                <code>edm</code>
                <label>Editor of moving image work</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/edt</uri>
                <code>edt</code>
                <label>Editor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/egr</uri>
                <code>egr</code>
                <label>Engraver</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/elg</uri>
                <code>elg</code>
                <label>Electrician</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/elt</uri>
                <code>elt</code>
                <label>Electrotyper</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/eng</uri>
                <code>eng</code>
                <label>Engineer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/enj</uri>
                <code>enj</code>
                <label>Enacting jurisdiction</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/etr</uri>
                <code>etr</code>
                <label>Etcher</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/evp</uri>
                <code>evp</code>
                <label>Event place</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/exp</uri>
                <code>exp</code>
                <label>Expert</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/fac</uri>
                <code>fac</code>
                <label>Facsimilist</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/fds</uri>
                <code>fds</code>
                <label>Film distributor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/fld</uri>
                <code>fld</code>
                <label>Field director</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/flm</uri>
                <code>flm</code>
                <label>Film editor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/fmd</uri>
                <code>fmd</code>
                <label>Film director</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/fmk</uri>
                <code>fmk</code>
                <label>Filmmaker</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/fmo</uri>
                <code>fmo</code>
                <label>Former owner</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/fmp</uri>
                <code>fmp</code>
                <label>Film producer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/fnd</uri>
                <code>fnd</code>
                <label>Funder</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/fpy</uri>
                <code>fpy</code>
                <label>First party</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/frg</uri>
                <code>frg</code>
                <label>Forger</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/gis</uri>
                <code>gis</code>
                <label>Geographic information specialist</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/his</uri>
                <code>his</code>
                <label>Host institution</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/hnr</uri>
                <code>hnr</code>
                <label>Honoree</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/hst</uri>
                <code>hst</code>
                <label>Host</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ill</uri>
                <code>ill</code>
                <label>Illustrator</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ilu</uri>
                <code>ilu</code>
                <label>Illuminator</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ins</uri>
                <code>ins</code>
                <label>Inscriber</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/inv</uri>
                <code>inv</code>
                <label>Inventor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/isb</uri>
                <code>isb</code>
                <label>Issuing body</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/itr</uri>
                <code>itr</code>
                <label>Instrumentalist</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ive</uri>
                <code>ive</code>
                <label>Interviewee</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ivr</uri>
                <code>ivr</code>
                <label>Interviewer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/jud</uri>
                <code>jud</code>
                <label>Judge</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/jug</uri>
                <code>jug</code>
                <label>Jurisdiction governed</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/lbr</uri>
                <code>lbr</code>
                <label>Laboratory</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/lbt</uri>
                <code>lbt</code>
                <label>Librettist</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ldr</uri>
                <code>ldr</code>
                <label>Laboratory director</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/led</uri>
                <code>led</code>
                <label>Lead</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/lee</uri>
                <code>lee</code>
                <label>Libelee-appellee</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/lel</uri>
                <code>lel</code>
                <label>Libelee</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/len</uri>
                <code>len</code>
                <label>Lender</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/let</uri>
                <code>let</code>
                <label>Libelee-appellant</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/lgd</uri>
                <code>lgd</code>
                <label>Lighting designer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/lie</uri>
                <code>lie</code>
                <label>Libelant-appellee</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/lil</uri>
                <code>lil</code>
                <label>Libelant</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/lit</uri>
                <code>lit</code>
                <label>Libelant-appellant</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/lsa</uri>
                <code>lsa</code>
                <label>Landscape architect</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/lse</uri>
                <code>lse</code>
                <label>Licensee</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/lso</uri>
                <code>lso</code>
                <label>Licensor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ltg</uri>
                <code>ltg</code>
                <label>Lithographer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/lyr</uri>
                <code>lyr</code>
                <label>Lyricist</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/mcp</uri>
                <code>mcp</code>
                <label>Music copyist</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/mdc</uri>
                <code>mdc</code>
                <label>Metadata contact</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/med</uri>
                <code>med</code>
                <label>Medium</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/mfp</uri>
                <code>mfp</code>
                <label>Manufacture place</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/mfr</uri>
                <code>mfr</code>
                <label>Manufacturer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/mod</uri>
                <code>mod</code>
                <label>Moderator</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/mon</uri>
                <code>mon</code>
                <label>Monitor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/mrb</uri>
                <code>mrb</code>
                <label>Marbler</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/mrk</uri>
                <code>mrk</code>
                <label>Markup editor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/msd</uri>
                <code>msd</code>
                <label>Musical director</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/mte</uri>
                <code>mte</code>
                <label>Metal-engraver</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/mtk</uri>
                <code>mtk</code>
                <label>Minute taker</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/mus</uri>
                <code>mus</code>
                <label>Musician</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/nrt</uri>
                <code>nrt</code>
                <label>Narrator</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/opn</uri>
                <code>opn</code>
                <label>Opponent</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/org</uri>
                <code>org</code>
                <label>Originator</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/orm</uri>
                <code>orm</code>
                <label>Organizer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/osp</uri>
                <code>osp</code>
                <label>Onscreen presenter</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/oth</uri>
                <code>oth</code>
                <label>Other</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/own</uri>
                <code>own</code>
                <label>Owner</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/pan</uri>
                <code>pan</code>
                <label>Panelist</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/pat</uri>
                <code>pat</code>
                <label>Patron</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/pbd</uri>
                <code>pbd</code>
                <label>Publishing director</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/pbl</uri>
                <code>pbl</code>
                <label>Publisher</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/pdr</uri>
                <code>pdr</code>
                <label>Project director</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/pfr</uri>
                <code>pfr</code>
                <label>Proofreader</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/pht</uri>
                <code>pht</code>
                <label>Photographer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/plt</uri>
                <code>plt</code>
                <label>Platemaker</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/pma</uri>
                <code>pma</code>
                <label>Permitting agency</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/pmn</uri>
                <code>pmn</code>
                <label>Production manager</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/pop</uri>
                <code>pop</code>
                <label>Printer of plates</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ppm</uri>
                <code>ppm</code>
                <label>Papermaker</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ppt</uri>
                <code>ppt</code>
                <label>Puppeteer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/pra</uri>
                <code>pra</code>
                <label>Praeses</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/prc</uri>
                <code>prc</code>
                <label>Process contact</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/prd</uri>
                <code>prd</code>
                <label>Production personnel</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/pre</uri>
                <code>pre</code>
                <label>Presenter</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/prf</uri>
                <code>prf</code>
                <label>Performer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/prg</uri>
                <code>prg</code>
                <label>Programmer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/prm</uri>
                <code>prm</code>
                <label>Printmaker</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/prn</uri>
                <code>prn</code>
                <label>Production company</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/pro</uri>
                <code>pro</code>
                <label>Producer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/prp</uri>
                <code>prp</code>
                <label>Production place</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/prs</uri>
                <code>prs</code>
                <label>Production designer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/prt</uri>
                <code>prt</code>
                <label>Printer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/prv</uri>
                <code>prv</code>
                <label>Provider</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/pta</uri>
                <code>pta</code>
                <label>Patent applicant</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/pte</uri>
                <code>pte</code>
                <label>Plaintiff-appellee</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ptf</uri>
                <code>ptf</code>
                <label>Plaintiff</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/pth</uri>
                <code>pth</code>
                <label>Patent holder</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ptt</uri>
                <code>ptt</code>
                <label>Plaintiff-appellant</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/pup</uri>
                <code>pup</code>
                <label>Publication place</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/rbr</uri>
                <code>rbr</code>
                <label>Rubricator</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/rcd</uri>
                <code>rcd</code>
                <label>Recordist</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/rce</uri>
                <code>rce</code>
                <label>Recording engineer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/rcp</uri>
                <code>rcp</code>
                <label>Addressee</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/rdd</uri>
                <code>rdd</code>
                <label>Radio director</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/red</uri>
                <code>red</code>
                <label>Redaktor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ren</uri>
                <code>ren</code>
                <label>Renderer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/res</uri>
                <code>res</code>
                <label>Researcher</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/rev</uri>
                <code>rev</code>
                <label>Reviewer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/rpc</uri>
                <code>rpc</code>
                <label>Radio producer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/rps</uri>
                <code>rps</code>
                <label>Repository</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/rpt</uri>
                <code>rpt</code>
                <label>Reporter</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/rpy</uri>
                <code>rpy</code>
                <label>Responsible party</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/rse</uri>
                <code>rse</code>
                <label>Respondent-appellee</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/rsg</uri>
                <code>rsg</code>
                <label>Restager</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/rsp</uri>
                <code>rsp</code>
                <label>Respondent</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/rsr</uri>
                <code>rsr</code>
                <label>Restorationist</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/rst</uri>
                <code>rst</code>
                <label>Respondent-appellant</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/rth</uri>
                <code>rth</code>
                <label>Research team head</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/rtm</uri>
                <code>rtm</code>
                <label>Research team member</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/sad</uri>
                <code>sad</code>
                <label>Scientific advisor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/sce</uri>
                <code>sce</code>
                <label>Scenarist</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/scl</uri>
                <code>scl</code>
                <label>Sculptor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/scr</uri>
                <code>scr</code>
                <label>Scribe</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/sds</uri>
                <code>sds</code>
                <label>Sound designer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/sec</uri>
                <code>sec</code>
                <label>Secretary</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/sgd</uri>
                <code>sgd</code>
                <label>Stage director</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/sgn</uri>
                <code>sgn</code>
                <label>Signer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/sht</uri>
                <code>sht</code>
                <label>Supporting host</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/sll</uri>
                <code>sll</code>
                <label>Seller</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/sng</uri>
                <code>sng</code>
                <label>Singer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/spk</uri>
                <code>spk</code>
                <label>Speaker</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/spn</uri>
                <code>spn</code>
                <label>Sponsor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/spy</uri>
                <code>spy</code>
                <label>Second party</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/srv</uri>
                <code>srv</code>
                <label>Surveyor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/std</uri>
                <code>std</code>
                <label>Set designer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/stg</uri>
                <code>stg</code>
                <label>Setting</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/stl</uri>
                <code>stl</code>
                <label>Storyteller</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/stm</uri>
                <code>stm</code>
                <label>Stage manager</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/stn</uri>
                <code>stn</code>
                <label>Standards body</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/str</uri>
                <code>str</code>
                <label>Stereotyper</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/tcd</uri>
                <code>tcd</code>
                <label>Technical director</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/tch</uri>
                <code>tch</code>
                <label>Teacher</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/ths</uri>
                <code>ths</code>
                <label>Thesis advisor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/tld</uri>
                <code>tld</code>
                <label>Television director</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/tlp</uri>
                <code>tlp</code>
                <label>Television producer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/trc</uri>
                <code>trc</code>
                <label>Transcriber</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/trl</uri>
                <code>trl</code>
                <label>Translator</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/tyd</uri>
                <code>tyd</code>
                <label>Type designer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/tyg</uri>
                <code>tyg</code>
                <label>Typographer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/uvp</uri>
                <code>uvp</code>
                <label>University place</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/vac</uri>
                <code>vac</code>
                <label>Voice actor</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/vdg</uri>
                <code>vdg</code>
                <label>Videographer</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/wac</uri>
                <code>wac</code>
                <label>Writer of added commentary</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/wal</uri>
                <code>wal</code>
                <label>Writer of added lyrics</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/wam</uri>
                <code>wam</code>
                <label>Writer of accompanying material</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/wat</uri>
                <code>wat</code>
                <label>Writer of added text</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/wdc</uri>
                <code>wdc</code>
                <label>Woodcutter</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/wde</uri>
                <code>wde</code>
                <label>Wood engraver</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/win</uri>
                <code>win</code>
                <label>Writer of introduction</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/wit</uri>
                <code>wit</code>
                <label>Witness</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/wpr</uri>
                <code>wpr</code>
                <label>Writer of preface</label>
            </relator>
            <relator>
                <uri>http://id.loc.gov/vocabulary/relators/wst</uri>
                <code>wst</code>
                <label>Writer of supplementary textual content</label>
            </relator>
        </relators>
    </xsl:variable>
    
</xsl:stylesheet>